#!/bin/bash
#Git删除当前分支下的所有历史版本与log并同步至GitHub

git checkout --orphan latest_branch
git add -A
git commit -am "clean history"
git branch -D master
git branch -m master
git push -f origin master
git push --set-upstream origin master